title:              Sean Yi
email:              sean.yi@mail.utoronto.ca
description:        Back-End Developer | Data Scientist
author:             Seo Won Yi (Sean)
baseurl:            ""
url:                "https://woom221.github.io"

# Social Profiles
twitter_username:   
github_username:    woom221
facebook_username:  
instagram_username:  
linkedin_username: "sean-y-781701136"

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
